/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: phongle (https://sketchfab.com/phongledesigner)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/triipbox-update-6bd04300e3fd423fa944690afb3854f3
title: TRIIPBOX Update
*/

import React, { useRef } from 'react';
import { useGLTF, useAnimations } from '@react-three/drei';

export default function Model(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF('/gift.gltf');
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} scale={2} dispose={null}>
      <group name='Sketchfab_Scene'>
        <group name='Sketchfab_model' rotation={[-Math.PI / 2, 0, 0]}>
          <group name='root'>
            <group name='GLTF_SceneRootNode' rotation={[Math.PI / 2, 0, 0]}>
              <group name='Curve002_89' position={[0.03, 0.72, -0.02]} rotation={[1.57, 0, 3.14]} scale={4.24}>
                <mesh name='Object_95' castShadow receiveShadow geometry={nodes.Object_95.geometry} material={materials['SVGMat.001']} />
                <mesh name='Object_96' castShadow receiveShadow geometry={nodes.Object_96.geometry} material={materials['Material.001']} />
                <mesh name='Object_97' castShadow receiveShadow geometry={nodes.Object_97.geometry} material={materials.SVGMat} />
              </group>
              <group name='giftJnts_88' rotation={[Math.PI / 2, 0, Math.PI / 2]} scale={0.1}>
                <group name='GLTF_created_0'>
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <group name='gift_87' />
                  <skinnedMesh name='Object_7' geometry={nodes.Object_7.geometry} material={materials.blinn1} skeleton={nodes.Object_7.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload('/gift.gltf');
